parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     skical
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_encryption: ssl
    mailer_auth_mode:  login
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
